### ISSUE TITLE
Is there a way programmatically to rerun the line above if the exception error occurred?

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#29] opened 2020-02-26 08:46 UTC
@WK-GiHu, sir,Also, I'm having an error in fingerprint scanner it's a hardware issue because of the wiring. even if the program is running when the error occurred it will stop running. To make it work again I have to rerun the program again... Is there a way programmatically to rerun the line above if the exception error occurred?  
```
 try:
            f = PyFingerprint('/dev/ttyUSB0', 57600, 0xFFFFFFFF, 0x00000000)

            if ( f.verifyPassword() == False ):
                raise ValueError('The given fingerprint sensor password is wrong!')
```

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/28#issuecomment-591187528_

**Comment by WK-GiHu** [comment] 2020-02-26 08:56
@Justinjay282 

>Is there a way programmatically to rerun the line above if the exception error occurred?

It's hard to accomplish, you need.
1. Catch the error
2. Stop the background task
3. Detect the error is gone, either by retry forever/x-times or user confirmation.
4. The main program have to wait until the background task have succesfully started or ignor/assume it.

Start with point **1.** and a message that tells failure, without stopping the main program.

**Comment by Justinjay282** [comment] 2020-02-26 09:07
sir, @WK-GiHu,
I'm sorry sir, I was wrong, the error is in `while(f.readImage() == False):` inside the `while True`, not on the code I've shown you above.

 here's the error I've encountered.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Thesis/Thesis_Revised.py", line 66, in run
    while ( f.readImage() == False ):
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 654, in readImage
    receivedPacket = self.__readPacket()
  File "/usr/lib/python3/dist-packages/pyfingerprint/pyfingerprint.py", line 300, in __readPacket
    raise Exception('The received packet do not begin with a valid header!')
Exception: The received packet do not begin with a valid header!
```
when this error occurred. the fingerprint scanner device light will turn off. If I rerun the program It's going back to normal...

**Comment by WK-GiHu** [comment] 2020-02-26 13:11
@Justinjay282 

>Exception: The received packet do not begin with a valid header!

Seems no hardware `Exception`, ok catch it and try simple to read again using `while ( f.readImage() == False ):`. 
```
# Retry 3-times
retry = 0
while True:
    retry += 1
    try:
        while ( f.readImage() == False ):
                # delay 1 second
                time.sleep(1)
        # No exception, break while and continue
        break
    except Exception as e:
         print('PyFingerprint:{}, try {} of 3'.format(e, retry))
         if retry == 3:
             raise Exception('PyFingerprint: Faild to read image 3 times, exiting.')

         # delay 2 seconds before next try
         time.sleep(2)
```

**Comment by Justinjay282** [comment] 2020-02-26 13:31
sir, @WK-GiHu, I've committed the changes in `Kiosk_Main.py` The result is, the fingerprint light is blinking every 1 sec (because of the delay) but if I scanned my finger I cannot scan anymore and the login failed or successful is not popping. Also, the error is not always showing, I mean It's not giving me an error suddenly without me noticing. but sometimes I running it. The said error is not showing.

**Comment by WK-GiHu** [comment] 2020-02-26 14:22
@Justinjay282 

You have replaced the **outer `while ...`** , this was not intensional, should read:
```
# outer running forever mainloop of the background task
while True:
    # Retry 3-times
    retry = 0
   # inner retry loop
    while True:
        retry += 1
        ...
        try:
            # the read loop until success or exception
            while ( f.readImage() == False ):
                ....
            # No exception, break the inner retry while and continue
            break
            ...

    # continue with the background task
```
  https://github.com/Justinjay282/qwerty/blob/ec0572be690f86aac890d3d0afdf5998914a548e/Kiosk_Main.py#L49

**Comment by Justinjay282** [comment] 2020-02-27 07:03
sir, @WK-GiHu, it's working. But I'm not encountering the error yet. But it's back to normal when I commited the changes above.

**Comment by WK-GiHu** [comment] 2020-02-27 09:36
@Justinjay282 

>t's working. But I'm not encountering the error yet. But it's back to normal when I commited the changes above.

OK

Did you see this output?
```
print('PyFingerprint:{}, try {} of 3'.format(e, retry))
```

**Comment by Justinjay282** [comment] 2020-02-27 15:57
@WK-GiHu, sir, I'm not seeing the output yet. I didn't turn off the program and let it open for more than 5 hours. and the error didn't occur. maybe the error is somehow connected to the wires. Sometimes, when I scanned the fingerprint will turn-off but there's no error.

**Comment by WK-GiHu** [comment] 2020-02-27 17:49
@Justinjay282 

> the error didn't occur. ... Sometimes, when I scanned the fingerprint will turn-off but there's no error

OK, i hope the error will not occur at demonstation time.

>I will do the upload of an image to the database and that image will be displayed in SplashScreen. Last time I'm having trouble displaying an image from the database when I put the image in __init__

The `class SplashScreen` is gone from `Kiosk_Main.py` cant't review.
Did you obey: [Why does Tkinter image not show up if created in a function?](https://stackoverflow.com/a/16424553/7414759)

>Can I put your name in our acknowledgments when we're done in our thesis?

You can use `SO:stovfl` or `WK-GiHu` or both.

**Comment by Justinjay282** [comment] 2020-02-28 04:14
Hi sir, @WK-GiHu, I think the statements you suggest about the 
`PyFingerprint:The received packet do not begin with a valid header!, try 0 of 3` is working. When my fingerprint scanner turned off, I waited a couple of seconds, the 
```
PyFingerprint:The received packet do not begin with a valid header!, try 0 of 3
```
printed out and It's working again. THANK YOU SO MUCH! :) 

> Did you obey:...

I will obey what you taught me last time, I will do it once we have confirmed the decision of our adviser since He suggested a lot, and some of them are out of our ability or impossible for us to do.
>You can use `SO:stovfl` or `WK-GiHu` or both.

Can I get your full name, sir? so we can give you a credit for helping us do this :)

**Comment by WK-GiHu** [comment] 2020-02-28 15:30
@Justinjay282 

>When my fingerprint scanner turned off, I waited a couple of seconds, the
`PyFingerprint:The received packet do not begin with a valid header!, try 0 of 3`
printed out and It's working again.

OK, lucky case.
But sould read `try 1 of 3`
There is a missing increment, can lead to infinite loop. Insert above Line 38: `retry += 1`
https://github.com/Justinjay282/qwerty/blob/1522d8a0bae7903a8d43a8da8d3ffc13a48bf03c/Kiosk_Main.py#L38

>Can I get your full name, sir?

I want to be *Anonymous*, you can only use my *Alias*.

**Comment by Justinjay282** [comment] 2020-02-29 11:08
sir, @WK-GiHu, I've edited the code in the `repository`

> I want to be Anonymous, you can only use my Alias.

I respect your decision sir, I just ask to give you proper credit, but this will do thank you so much. I am not yet sure if I can finish this. But I will do my best to not waste your effort in helping us :) again, Thank you so much, Sir!

**Comment by Justinjay282** [comment] 2020-03-12 02:50
sir @WK-GiHu, I have a problem, sir. Since the fingerprint scanner is always running on the background thread. I'm having an error if I registered a fingerprint. I can't actually detect the error, the recent I've received is.
```
Exception message: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
since I'm gonna use the same fingerprint device for login I really need to fix this.
Hoping for your reply again sir.thank you so much!

**Comment by WK-GiHu** [comment] 2020-03-12 11:29
@Justinjay282 

>`Exception message: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

Seems the reason is: ***multiple access on port?***
Indeed, you are have **multiple access on port?**, so rerun will not change anything.
Does it even work **once**?
I guess it will fail at once.

>Since the fingerprint scanner is always running on the background thread.

Yes, can't you resuse this background `Thread`?

I don't get the schema of what you are doing in `update_residents_fingerprint.py` so please describe the codeflow, e.g. 1. do this, 2. do that, 3. do again this.

**Comment by Justinjay282** [comment] 2020-03-12 11:45
sir @WK-GiHu, yes the reason is **multiple access on port?**.  I think since, the `FingerprintThread` is always running in the background it's having a problem if I run the same fingerprint scanner and use it differently.

> * [ ]  Does it even work **once**?

the fingerprint login is working as long as the `update fingerprint button` is not pressed.

> * [ ]  Does it work **standalone**, only running `update_residents_fingerprint.py`?

if the `update fingerprint button` was pressed it will work but after scanning the finger the error will pop and the background thread is also having a problem.

> You can stop and restart the background `Thread`, this requires to add a terminate condition
> * [ ]  Yes i want this solution

I will accept any solution regarding this problem sir. 
but is it able to do the `fingerprintThread` and `RFIDthread` will only run if I'm on a login window/page?

> I don't get the schema of what you are doing in `update_residents_fingerprint.py` so please describe the codeflow, e.g. 1. do this, 2. do that, 3. do again this.


the `update_residents_fingerprint.py` is a top-level window to display the data from database to treeview, I have 2 buttons there the `reset button` and the `update fingerprint button` If I clicked the `update fingerprint button` another `toplevel window` will appear with a background `scan fingerprint to register` I used label.bind("<Enter>", callback" to call another method that will register the scanned finger to the database. But it's not working since the Fingerprint is already running in the background.

**Comment by WK-GiHu** [comment] 2020-03-12 14:59
@Justinjay282 

>> Does it work standalone, only running `update_residents_fingerprint.py`?
>
>if the update fingerprint button was pressed it will work but after scanning the finger the error will pop and the background thread is also having a problem.

### This does not answer my question.

Run `update_residents_fingerprint.py` standalone to verify.

Please try to answer my question as you are doing multiple `f = PyFingerprint(...` withou closing `f` which is also **multiple access on port**:
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/update_resident_fingerprint.py#L131
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/update_resident_fingerprint.py#L150
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/update_resident_fingerprint.py#L205

---

The cleanest way is, to implement **one** `class PyFingerprint(` and reuse it in the background `Thread` and in `update_residents_fingerprint.py`

I recommend this strong!

---

## First you have to verify

 if it's posible and safe to interrupted `f.readImage()`!

Do you have any link to the Documentation about `PyFingerprint.readImage()`.
I have to know if the method `.readImage()` is blocking or not.
Alternativ, you can verify by adding `print('looping .readImage()')` above line 165
https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/update_resident_fingerprint.py#L165
If you see multiple prints, it's not blocking.

---

>the update_residents_fingerprint.py is a top-level window 

OK, that's a well-defined entry point in `class Update_residents`.
There you can place a call to **stop** the background `Thread`.

You have to extend the `class Update_residents` with a defined `close` function.
Do accordingly like here: [doing-tasks-when-a-tkinter-application-is-closed](https://stackoverflow.com/questions/48603066)
There you can place a call to **restart** the background `Thread`.

---

**Comment by Justinjay282** [comment] 2020-03-12 15:19
> @Justinjay282
> 
> > > Does it work standalone, only running `update_residents_fingerprint.py`?
> > 
> > 
> > if the update fingerprint button was pressed it will work but after scanning the finger the error will pop and the background thread is also having a problem.
> 
> ### This does not answer my question.
> Run `update_residents_fingerprint.py` standalone to verify.
> 
> Please try to answer my question as you are doing multiple `f = PyFingerprint(...` withou closing `f` which is also **multiple access on port**:
> 

I run it independently without the `background thread` it's working fine. I tested it while the `FingerprintThread` is active and it also runs. I can't guess if both `f = PyFingerprint('/dev/ttyUSB0', 57600,0xFFFFFFFF, 0x0000000)` is working I tried it. The fingerprint scanner blinked and I can now register a finger. Since I used `label.bind("Enter", callback)` with successful register the `FingerprintThread` started running then a couple of seconds the **multiple ports** error appeared. tried it again, the `FingerprintThread` work as a login while having a `scanfingerprint to register window` and then the error **multiple port appeared**

> The cleanest way is, to implement **one** `class PyFingerprint(` and reuse it in the background `Thread` and in `update_residents_fingerprint.py`
> 
> I recommend this strong!
> 

I'll do what you'll recommend sir!

> ## First you have to verify
> if it's posible and safe to interrupted `f.readImage()`!
> 
> Do you have any link to the Documentation about `PyFingerprint.readImage()`.
> I have to know if the method `.readImage()` is blocking or not.
> Alternativ, you can verify by adding `print('looping .readImage()')` above line 165
> https://github.com/Justinjay282/qwerty/blob/071a96586f79e9d8fd164c05c20a01bc6a4b0df4/update_resident_fingerprint.py#L165
> 
> 
> If you see multiple prints, it's not blocking.

I put `print(looping)` and it's printing non-stop.

**Closed** 2020-03-15 11:39 UTC
